### ISSUE TITLE
app is not working with kodi v20.1

### ISSUE THREAD

**Issue by jryan15** [Spinalcracker/infowars#5]
Hi there,

Thanks so much for supporting this addon!  I was forced to upgrade to kodi v20.1 and am getting an error trying to use the addon.  Any chance someone can help?

`2023-06-13 00:19:00.426 T:24528   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\HTPC\AppData\Roaming\Kodi\addons\plugin.video.banned.video\default.py", line 37, in <module>
                                                       xbmc.translatePath("special://database"), 'infowars.db')
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--
                                                   
2023-06-13 00:19:00.584 T:9712     info <general>: Loading skin file: DialogTextViewer.xml, load type: KEEP_IN_MEMORY
2023-06-13 00:19:00.592 T:10272   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.banned.video/
2023-06-13 00:19:05.187 T:9712    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.banned.video/) failed
2`

Thanks!
